"""update tables

Revision ID: c0e43afe17d2
Revises: 0d7fa08a6003
Create Date: 2026-09-11 14:18:04.685371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e43afe17d2'
down_revision: Union[str, Sequence[str], None] = '0d7fa08a6003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('costs_user_id_fkey'), 'costs', type_='foreignkey')
    op.create_foreign_key(None, 'costs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_fake', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_fake')
    op.drop_constraint(None, 'costs', type_='foreignkey')
    op.create_foreign_key(op.f('costs_user_id_fkey'), 'costs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
